langchain4j.vertex-ai-gemini:
  chat-model:
    model-name: gemini-1.5-flash
    project: gen-lang-client-0387603682
    location: us-central1
    enabled: true
spring:
  data:
    mongodb:
      username: root
      password: root
      authentication-database: admin